name: maia-cloud-clean
region: tor
services:
  - name: maia-app
    source_dir: /
    github:
      repo: agropper/maia-cloud-clean
      branch: main
    build_command: npm install --include=dev && npm run build
    run_command: node server.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3001
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: DIGITALOCEAN_PERSONAL_API_KEY
        value: "your-digitalocean-personal-api-key"
      - key: ANTHROPIC_API_KEY
        value: "your-anthropic-api-key"
      - key: OPENAI_API_KEY
        value: "your-openai-api-key"
      - key: DEEPSEEK_API_KEY
        value: "your-deepseek-api-key"
      - key: GEMINI_API_KEY
        value: "your-gemini-api-key"
      - key: DIGITALOCEAN_GENAI_ENDPOINT
        value: "https://vzfujeetn2dkj4d5awhvvibo.agents.do-ai.run/api/v1"
      - key: DIGITALOCEAN_TOKEN
        value: "your-digitalocean-token"
      - key: DIGITALOCEAN_BASE_URL
        value: "https://api.digitalocean.com"
      - key: DIGITALOCEAN_PROJECT_ID
        value: ""
      - key: ALLOWED_ORIGINS
        value: "https://maia.adriang.xyz,https://maia-cloud-clean-kjho4.ondigitalocean.app"
      - key: ENABLE_REQUEST_LOGGING
        value: "true"
      - key: SINGLE_PATIENT_MODE
        value: "false"
      - key: DEFAULT_AGENT
        value: "agent-05102025"
      - key: ORIGIN
        value: "https://maia.adriang.xyz"
      - key: COUCHDB_URL
        value: "https://101aa9c8-aee0-475f-b6c0-cd5b68e28c24-bluemix.cloudantnosqldb.appdomain.cloud"
      - key: COUCHDB_USERNAME
        value: "apikey-v2-eddelp7dcgxzao6urqtv5g5fp8802s6dbsuovnyy8ia"
      - key: COUCHDB_PASSWORD
        value: "21340f475d40052c304a36aac046df3a"
      - key: COUCHDB_DATABASE
        value: "maia_chats"
      - key: CLOUDANT_URL
        value: "https://101aa9c8-aee0-475f-b6c0-cd5b68e28c24-bluemix.cloudantnosqldb.appdomain.cloud"
      - key: CLOUDANT_USERNAME
        value: "apikey-v2-eddelp7dcgxzao6urqtv5g5fp8802s6dbsuovnyy8ia"
      - key: CLOUDANT_PASSWORD
        value: "21340f475d40052c304a36aac046df3a"
      - key: CLOUDANT_DATABASE
        value: "maia_chats"
      - key: VITE_API_BASE_URL
        value: "/api" 