name: maia-cloud-clean
region: tor
services:
  - name: maia-app
    source_dir: /
    github:
      repo: agropper/maia-cloud-clean
      branch: main
    dockerfile_path: Dockerfile
    run_command: node server.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3001
    routes:
      - path: / 